name: CI to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        mediawiki_version: [1.31, 1.35, 1.36]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve MediaWiki version
        run: |
          echo ::set-env name=TAG_NAME::$(cat ./${{ matrix.mediawiki_version }}/Dockerfile | sed -n -e 's/^.*FROM mediawiki://p')
          echo ${{ env.TAG_NAME }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/${{ matrix.mediawiki_version }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ matrix.mediawiki_version }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: gesinn/docker-mediawiki:${{ matrix.mediawiki_version }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.mediawiki_version }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.mediawiki_version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
